const FpmMulcariList = [
    {
        _id: '1',
        nameUrl: 'vocarski-mulcari-618-1',
        productHeader: 'Voćarski Mulčari FPM 618.103 - 618.117',
        className: `fpm-vocarski-mulcari-img`,
        desc1: 'Voćarski mulčari spadaju u grupu poljoprivrednih mulčara i prvenstveno su namenjeni za usitnjavanje biljnih ostataka nakon rezidbe..',
        desc2: 'Voćarski mulčari spadaju u grupu poljoprivrednih mulčara i prvenstveno su namenjeni za usitnjavanje biljnih ostataka nakon rezidbe, kao i korova i trave u voćnjacima i vinogradima.',

        teh_kar: 'Tehničke Karakteristike',
        t1LeftHeader: 'FPM 618.103 - 618.117',
        desc3: 'Pored svoje osnovne namene mogu se koristiti i za usitnjavanje biljne mase, uređivanje i održavanje svih drugih poljoprivrednih, komunalnih, zapuštenih i neobrađenih površina. Zahvaljujući velikoj brzini rotora, koji je elektronski balansiran, noževi precizno i efikasno usitnjavaju biljne ostatke i tako ih pretvaraju u lako humusno đubrivo, čime se poboljšava kvalitet i prirodna plodnost zemljišta, a smanjuje potreba za veštačkim đubrenjem. Na taj način se direktno utiče na smanjenje troškova poljoprivredne proizvodnje i povećanje prinosa',

        table1: [
            'Tip',
            '618.103 | FPM 618.117',
            'Radni zahvat (m)',
            '1,55 | 1,55',
            'Ukupna širina (m)',
            '1,7 | 1,7',
            'Minimalna snaga traktora-kw(ks)',
            '18(25) | 18(25)',
            'Priključivanje',
            'U tri tačke',
            'Kategorija traktora',
            'I,II',
            'Broj obrtaja izlaznog vratila traktora (o/min)',
            '540',
            'Broj obrtaja rotora (o/min)',
            '2230',
            'Prečnik rotora (mm)',
            '108',
            'Prečnik rotora sa noževima (mm)',
            '350',
            'Bočni prenos',
            'Klinasti kaiševi (3 komada)',
            'Standardni nož',
            'čekić',
            'Broj noževa čekić',
            '16',
            'Broj noževa Y',
            '48',
            'Podešavanje visine',
            'valjak,bočni klizači ',
            'Visina reza (cm)',
            '2-7',
            'Način pomeranja u stranu',
            'mehaničko | hidraulično',
            'Težina (kg)',
            '310 | 320',
        ],

        standardOprema1: 'Prednosti',
        standardLi1: [
            ' - Usitnjava granje do 50 mm debljine',
            ' - Niska potrošnja goriva i potrebna mala snaga traktora, zahvaljujući duplo spiralnom i optimalnom rasporedu noževa na rotoru',
            ' - Bočno pomeranje',
            ' - Niski troškovi i jednostavno održavanje'
        ],

        standardOprema2: 'Glavne karakteristike:',
        standardLi2: [
            ' - 1. Podešavanje visine pomoću bočnog klizača i/ili valjka.',
            ' - 2. Multiplikator sa jednosmernom spojnicom:',
            ' a) Zadnje kačenje (standardno);',
            ' b) Samo prednje ili kombinovano prednje i zadnje kačenje (opcija).',
            ' - 3. Pomeranje u stranu:',
            ' a) Mehaničko',
            ' b) Hidraulično',
            ' - 4. Opcije noževa:',
            ' a) Čekić-nož (standardni) – za teže radne uslove (granje, deblji korov, trava i slično)',
            ' b) Univerzalni Y nož (opcija) – za lakše radne uslove (trava, korov i slično).',
            ' - 5. Bočni prenos preko seta specijalnih nazubljenih klinastih kaiševa.',
            ' - 6. Kontranoževi (standardno) – njihovim podešavanjem određuje se stepen usitnjenosti biljne mase (tri pozicije).',
        ],

        brand: 'FPM Agromehanika',
        category: 'Mulčeri'
    },
    {
        _id: '2',
        nameUrl: 'vocarski-mulcari-618-2',
        productHeader: 'Voćarski Mulčari 618.104 - 618.118',
        className: `fpm-vocarski-mulcari-img`,
        desc1: 'Voćarski mulčari spadaju u grupu poljoprivrednih mulčara i prvenstveno su namenjeni za usitnjavanje biljnih ostataka nakon rezidbe..',
        desc2: 'Voćarski mulčari spadaju u grupu poljoprivrednih mulčara i prvenstveno su namenjeni za usitnjavanje biljnih ostataka nakon rezidbe, kao i korova i trave u voćnjacima i vinogradima.',

        teh_kar: 'Tehničke Karakteristike',
        t1LeftHeader: 'FPM 618.104 - 618.118',
        desc3: 'Pored svoje osnovne namene mogu se koristiti i za usitnjavanje biljne mase, uređivanje i održavanje svih drugih poljoprivrednih, komunalnih, zapuštenih i neobrađenih površina. Zahvaljujući velikoj brzini rotora, koji je elektronski balansiran, noževi precizno i efikasno usitnjavaju biljne ostatke i tako ih pretvaraju u lako humusno đubrivo, čime se poboljšava kvalitet i prirodna plodnost zemljišta, a smanjuje potreba za veštačkim đubrenjem. Na taj način se direktno utiče na smanjenje troškova poljoprivredne proizvodnje i povećanje prinosa',

        table1: [
            'Tip',
            '618.104 | FPM 618.118',
            'Radni zahvat (m)',
            '1,80 | 1,80',
            'Ukupna širina (m)',
            '2,0 | 2,0',
            'Minimalna snaga traktora-kw(ks)',
            '22(30) | 22(30)',
            'Priključivanje',
            'U tri tačke',
            'Kategorija traktora',
            'I,II',
            'Broj obrtaja izlaznog vratila traktora (o/min)',
            '540',
            'Broj obrtaja rotora (o/min)',
            '2230',
            'Prečnik rotora (mm)',
            '108',
            'Prečnik rotora sa noževima (mm)',
            '350',
            'Bočni prenos',
            'Klinasti kaiševi (3 komada)',
            'Standardni nož',
            'čekić',
            'Broj noževa čekić',
            '18',
            'Broj noževa Y',
            '60',
            'Podešavanje visine',
            'valjak,bočni klizači ',
            'Visina reza (cm)',
            '2-7',
            'Način pomeranja u stranu',
            'mehaničko | hidraulično',
            'Težina (kg)',
            '350 | 360',
        ],

        standardOprema1: 'Prednosti',
        standardLi1: [
            ' - Usitnjava granje do 50 mm debljine',
            ' - Niska potrošnja goriva i potrebna mala snaga traktora, zahvaljujući duplo spiralnom i optimalnom rasporedu noževa na rotoru',
            ' - Bočno pomeranje',
            ' - Niski troškovi i jednostavno održavanje'
        ],

        standardOprema2: 'Glavne karakteristike:',
        standardLi2: [
            ' - 1. Podešavanje visine pomoću bočnog klizača i/ili valjka.',
            ' - 2. Multiplikator sa jednosmernom spojnicom:',
            ' a) Zadnje kačenje (standardno);',
            ' b) Samo prednje ili kombinovano prednje i zadnje kačenje (opcija).',
            ' - 3. Pomeranje u stranu:',
            ' a) Mehaničko',
            ' b) Hidraulično',
            ' - 4. Opcije noževa:',
            ' a) Čekić-nož (standardni) – za teže radne uslove (granje, deblji korov, trava i slično)',
            ' b) Univerzalni Y nož (opcija) – za lakše radne uslove (trava, korov i slično).',
            ' - 5. Bočni prenos preko seta specijalnih nazubljenih klinastih kaiševa.',
            ' - 6. Kontranoževi (standardno) – njihovim podešavanjem određuje se stepen usitnjenosti biljne mase (tri pozicije).',
        ],

        brand: 'FPM Agromehanika',
        category: 'Mulčeri'
    },
    {
        _id: '3',
        nameUrl: 'ratarski-mulcari-618-1',
        productHeader: 'Ratarski Mulčari 618.999 - 618.058',
        className: `fpm-ratarski-mulcari-img`,
        desc1: 'Ratarski mulčari spadaju u grupu poljoprivrednih mulčara i prvenstveno su namenjeni za usitnjavanje biljnih ostataka nakon žetve..',
        desc2: 'Ratarski mulčari spadaju u grupu poljoprivrednih mulčara i prvenstveno su namenjeni za usitnjavanje biljnih ostataka nakon žetve ratarskih kultura, kao što su kukuruz, suncokret, slama, šećerna repa, uljana repica, pirinač i slično',

        teh_kar: 'Tehničke Karakteristike',
        t1LeftHeader: 'FPM 618.999 - 618.058',
        desc3: 'Pored svoje osnovne namene mogu se koristiti i za usitnjavanje biljne mase, uređivanje i održavanje svih drugih poljoprivrednih, komunalnih, zapuštenih i neobrađenih površina. Zahvaljujući velikoj brzini rotora, koji je elektronski balansiran, noževi precizno i efikasno usitnjavaju biljne ostatke i tako ih pretvaraju u lako humusno đubrivo, čime se poboljšava kvalitet i prirodna plodnost zemljišta, a smanjuje potreba za veštačkim đubrenjem. Na taj način se direktno utiče na smanjenje troškova poljoprivredne proizvodnje i povećanje prinosa.',

        table1: [
            'Tip',
            'FPM 618.999 | FPM 618.058',
            'Radni zahvat (m)',
            '1,6 | 2,3',
            'Ukupna širina (m)',
            '1,8 | 2,5',
            'Minimalna snaga traktora-kw(ks)',
            '30(40) | 44(60)',
            'Priključivanje',
            'U tri tačke',
            'Kategorija traktora',
            'II',
            'Broj obrtaja izlaznog vratila traktora (o/min)',
            '540',
            'Broj obrtaja rotora (o/min)',
            '2230',
            'Prečnik rotora (mm)',
            '194',
            'Prečnik rotora sa noževima (mm)',
            '605',
            'Bočni prenos',
            'Klinasti kaiševi (jedna strana, 4 komada)',
            'Standardni nož',
            'Univerzalni-Y',
            'Broj noževa Y',
            '32 | 48',
            'Opcioni noževi',
            'ravan,mlatilo,čekić',
            'Podešavanje visine',
            'valjak i bočni klizači |  točkovi (opcija valjak) i bočni klizači',
            'Visina reza (cm)',
            '2-10',
            'Težina (kg)',
            '700  | 755',
        ],

        standardOprema1: 'Prednosti',
        standardLi1: [
            ' - Univerzalna primena',
            ' - Snažna i masivna konstrukcija',
            ' - Sa univerzalnim Y noževima usitnjava biljnu masu do 50 mm debljine, a sa čekić -noževima do 80 mm debljine',
            ' - Niski troškovi i jednostavno održavanje'
        ],

        standardOprema2: 'Glavne karakteristike:',
        standardLi2: [
            ' - 1. Podešavanje visine rada:',
            ' a) Točkovi (standardno) ili valjak (opcija,standardno za FPM 618.999)',
            ' b) Bočni klizači',
            ' - 2. Bočni prenos preko seta specijalnih nazubljenih klinastih kaiševa.',
            ' a) Mašine sa radnim zahvatom od 4 metra i 5,6 metara imaju bočni prenos sa obe strane',
            ' - 3. Opcije noževa',
            ' a) Univerzalni Y nož – za sve tipove biljne mase, a posebno za: kukuruz, suncokret, šećernu repu, pamuk, travu, korov i slično',
            ' b) Ravan nož – pšenica, raž, ječam, ovas, pirinač i slično',
            ' c) Čekić-nož – za teške radne uslove, kao što su drvenasta i deblja biljna masa',
            ' - 4. Podešavanje ugla izbacivanja usitnjene mase preko usmerivača na zadnjem poklopcu (rasturanje ili sakupljanje).',
            ' - 5. Kontranoževi obezbeđuju veću usitnjenost biljne mase. Jedan set (red) predstavlja deo standardne ponude, a postoji i opcija ugradnje još jednog seta (preporučuje se za slamu i slično).',
            ' - 6. Transmisija od multiplikatora do bočnog prenosa (vratilo u uljnom kućištu).',
            ' - 7. Masivni točkovi i nosači točkova (modeli od 4 m i 5,6 m)',
            ' - 8. Masivne priključne tačke za priključivanje na traktore II i III kategorije (modeli od 4 m i 5,6 m).'
        ],

        brand: 'FPM Agromehanika',
        category: 'Mulčeri'
    },
    {
        _id: '4',
        nameUrl: 'ratarski-mulcari-618-2',
        productHeader: 'Ratarski Mulčari FPM 618.059 - 618.080',
        className: `fpm-ratarski-mulcari-img`,
        desc1: 'Ratarski mulčari spadaju u grupu poljoprivrednih mulčara i prvenstveno su namenjeni za usitnjavanje biljnih ostataka nakon žetve..',
        desc2: 'Ratarski mulčari spadaju u grupu poljoprivrednih mulčara i prvenstveno su namenjeni za usitnjavanje biljnih ostataka nakon žetve ratarskih kultura, kao što su kukuruz, suncokret, slama, šećerna repa, uljana repica, pirinač i slično',

        teh_kar: 'Tehničke Karakteristike',
        t1LeftHeader: 'FPM 618.059 - 618.080',
        desc3: 'Pored svoje osnovne namene mogu se koristiti i za usitnjavanje biljne mase, uređivanje i održavanje svih drugih poljoprivrednih, komunalnih, zapuštenih i neobrađenih površina. Zahvaljujući velikoj brzini rotora, koji je elektronski balansiran, noževi precizno i efikasno usitnjavaju biljne ostatke i tako ih pretvaraju u lako humusno đubrivo, čime se poboljšava kvalitet i prirodna plodnost zemljišta, a smanjuje potreba za veštačkim đubrenjem. Na taj način se direktno utiče na smanjenje troškova poljoprivredne proizvodnje i povećanje prinosa.',

        table1: [
            'Tip',
            'FPM 618.059 | FPM 618.080',
            'Radni zahvat (m)',
            '2,8 | 3,3',
            'Ukupna širina (m)',
            '3,0 | 3,5',
            'Minimalna snaga traktora-kw(ks)',
            '51(70) | 59(80)',
            'Priključivanje',
            'U tri tačke',
            'Kategorija traktora',
            'II',
            'Broj obrtaja izlaznog vratila traktora (o/min)',
            '540',
            'Broj obrtaja rotora (o/min)',
            '2230',
            'Prečnik rotora (mm)',
            '194',
            'Prečnik rotora sa noževima (mm)',
            '605',
            'Bočni prenos',
            'Klinasti kaiševi (jedna strana, 5 komada)',
            'Standardni nož',
            'Univerzalni-Y',
            'Broj noževa Y',
            '56 | 68',
            'Opcioni noževi',
            'ravan,mlatilo,čekić',
            'Podešavanje visine',
            'točkovi (opcija valjak) i bočni klizači |  točkovi i bočni klizači',
            'Visina reza (cm)',
            '2-10',
            'Težina (kg)',
            '840  | 980',
        ],

        standardOprema1: 'Prednosti',
        standardLi1: [
            ' - Univerzalna primena',
            ' - Snažna i masivna konstrukcija',
            ' - Sa univerzalnim Y noževima usitnjava biljnu masu do 50 mm debljine, a sa čekić -noževima do 80 mm debljine',
            ' - Niski troškovi i jednostavno održavanje'
        ],

        standardOprema2: 'Glavne karakteristike:',
        standardLi2: [
            ' - 1. Podešavanje visine rada:',
            ' a) Točkovi (standardno) ili valjak (opcija,standardno za FPM 618.999)',
            ' b) Bočni klizači',
            ' - 2. Bočni prenos preko seta specijalnih nazubljenih klinastih kaiševa.',
            ' a) Mašine sa radnim zahvatom od 4 metra i 5,6 metara imaju bočni prenos sa obe strane',
            ' - 3. Opcije noževa',
            ' a) Univerzalni Y nož – za sve tipove biljne mase, a posebno za: kukuruz, suncokret, šećernu repu, pamuk, travu, korov i slično',
            ' b) Ravan nož – pšenica, raž, ječam, ovas, pirinač i slično',
            ' c) Čekić-nož – za teške radne uslove, kao što su drvenasta i deblja biljna masa',
            ' - 4. Podešavanje ugla izbacivanja usitnjene mase preko usmerivača na zadnjem poklopcu (rasturanje ili sakupljanje).',
            ' - 5. Kontranoževi obezbeđuju veću usitnjenost biljne mase. Jedan set (red) predstavlja deo standardne ponude, a postoji i opcija ugradnje još jednog seta (preporučuje se za slamu i slično).',
            ' - 6. Transmisija od multiplikatora do bočnog prenosa (vratilo u uljnom kućištu).',
            ' - 7. Masivni točkovi i nosači točkova (modeli od 4 m i 5,6 m)',
            ' - 8. Masivne priključne tačke za priključivanje na traktore II i III kategorije (modeli od 4 m i 5,6 m).'
        ],

        brand: 'FPM Agromehanika',
        category: 'Mulčeri'
    },
    {
        _id: '5',
        nameUrl: 'ratarski-mulcari-618-3',
        productHeader: 'Ratarski Mulčari FPM 618.132 - 618.124',
        className: `fpm-ratarski-mulcari-img`,
        desc1: 'Ratarski mulčari spadaju u grupu poljoprivrednih mulčara i prvenstveno su namenjeni za usitnjavanje biljnih ostataka nakon žetve..',
        desc2: 'Ratarski mulčari spadaju u grupu poljoprivrednih mulčara i prvenstveno su namenjeni za usitnjavanje biljnih ostataka nakon žetve ratarskih kultura, kao što su kukuruz, suncokret, slama, šećerna repa, uljana repica, pirinač i slično',

        teh_kar: 'Tehničke Karakteristike',
        t1LeftHeader: 'FPM 618.132 - 618.124',
        desc3: 'Pored svoje osnovne namene mogu se koristiti i za usitnjavanje biljne mase, uređivanje i održavanje svih drugih poljoprivrednih, komunalnih, zapuštenih i neobrađenih površina. Zahvaljujući velikoj brzini rotora, koji je elektronski balansiran, noževi precizno i efikasno usitnjavaju biljne ostatke i tako ih pretvaraju u lako humusno đubrivo, čime se poboljšava kvalitet i prirodna plodnost zemljišta, a smanjuje potreba za veštačkim đubrenjem. Na taj način se direktno utiče na smanjenje troškova poljoprivredne proizvodnje i povećanje prinosa.',

        table1: [
            'Tip',
            'FPM 618.132 | FPM 618.124',
            'Radni zahvat (m)',
            '4 | 5,6',
            'Ukupna širina (m)',
            '4,5 | 6,1',
            'Minimalna snaga traktora-kw(ks)',
            '81(110) | 110(150)',
            'Priključivanje',
            'U tri tačke',
            'Kategorija traktora',
            'II/III',
            'Broj obrtaja izlaznog vratila traktora (o/min)',
            '540',
            'Broj obrtaja rotora (o/min)',
            '2230',
            'Prečnik rotora (mm)',
            '194',
            'Prečnik rotora sa noževima (mm)',
            '605 (2 rotora)',
            'Bočni prenos',
            'Klinasti kaiševi (obe strane, 4 komada po strani) | (5 komada po strani)',
            'Standardni nož',
            'Univerzalni-Y',
            'Broj noževa Y',
            '80 | 112',
            'Opcioni noževi',
            'ravan,čekić',
            'Podešavanje visine',
            'točkovi i bočni klizači',
            'Visina reza (cm)',
            '2-10',
            'Težina (kg)',
            '1980  | 2680',
        ],

        standardOprema1: 'Prednosti',
        standardLi1: [
            ' - Univerzalna primena',
            ' - Snažna i masivna konstrukcija',
            ' - Sa univerzalnim Y noževima usitnjava biljnu masu do 50 mm debljine, a sa čekić -noževima do 80 mm debljine',
            ' - Niski troškovi i jednostavno održavanje'
        ],

        standardOprema2: 'Glavne karakteristike:',
        standardLi2: [
            ' - 1. Podešavanje visine rada:',
            ' a) Točkovi (standardno) ili valjak (opcija,standardno za FPM 618.999)',
            ' b) Bočni klizači',
            ' - 2. Bočni prenos preko seta specijalnih nazubljenih klinastih kaiševa.',
            ' a) Mašine sa radnim zahvatom od 4 metra i 5,6 metara imaju bočni prenos sa obe strane',
            ' - 3. Opcije noževa',
            ' a) Univerzalni Y nož – za sve tipove biljne mase, a posebno za: kukuruz, suncokret, šećernu repu, pamuk, travu, korov i slično',
            ' b) Ravan nož – pšenica, raž, ječam, ovas, pirinač i slično',
            ' c) Čekić-nož – za teške radne uslove, kao što su drvenasta i deblja biljna masa',
            ' - 4. Podešavanje ugla izbacivanja usitnjene mase preko usmerivača na zadnjem poklopcu (rasturanje ili sakupljanje).',
            ' - 5. Kontranoževi obezbeđuju veću usitnjenost biljne mase. Jedan set (red) predstavlja deo standardne ponude, a postoji i opcija ugradnje još jednog seta (preporučuje se za slamu i slično).',
            ' - 6. Transmisija od multiplikatora do bočnog prenosa (vratilo u uljnom kućištu).',
            ' - 7. Masivni točkovi i nosači točkova (modeli od 4 m i 5,6 m)',
            ' - 8. Masivne priključne tačke za priključivanje na traktore II i III kategorije (modeli od 4 m i 5,6 m).'
        ],

        brand: 'FPM Agromehanika',
        category: 'Mulčeri'
    },
]


const InoBreziceMulceri = [
    {
        _id: '6',
        nameUrl: 'mulcer-mks-plus',
        productHeader: 'MKS Plus',
        className: `mulcer-mks-plus-img`,
        desc1: 'Mulčer MKS Plus – profesionalan mulčer za komunalne namene, u ratarstvu i voćarstvu. Potrebna snaga traktora: 35 – 80 kW',
        desc2: 'Profesionalni mulčer MKS Plus se upotrebljava u ratarstvu, voćarstvu i u komunalne namene za intenzivan rad. Koristi se za usitnjavanje trave i žbunja na zapuštenim terenima i grana do 6 cm.',

        teh_kar: 'Tehničke Karakteristike',
        t1LeftHeader: 'Mulčer MKS Plus',
        desc3: 'S njim možemo raditi iza traktora i pored traktora, čisti traktore i kanale. Radi pod uglom od – 65º do + 90º. Mulčer MKS Plus možemo koristiti kod mulčiranja nasipa u kombinaciji sa prednjim ELITE ili EURO. Tako radimo u jednom prohodu duple širine i s time štedimo na vremenu i potrošnji energije. Mulčer MKS Plus ima dupli plašt koji se može menjati. Zbog reduktora sa spoljne strane okvira mulčera imamo veći bočni pomak. Raspodela radnih tela na rotoru u duploj spirali štedi potrošnju energije do 24%.',

        table1: [
            'Model',
            '160 | 190 | 225',
            'Radna širina/ukupna širina (cm)',
            '162/197 | 192/243 | 227/278',
            'Efikasnost (ha/sat)',
            '1,0-1,6 | 1,2-1,9 | 1,6-2,3',
            'Preporučena snaga (kW/KS)',
            '35-50/50-70 | 53-70/70-95 | 60-80/80-110',
            'Minimalna težina traktora ( kg )',
            '2500 | 2700 | 2900',
            'Minimalna širina traktora ( cm )',
            '180 | 200 | 200',
            'Broj čekića ( kom )',
            '20	 | 24 | 28',
            'Visina odkosa min-max (mm)',
            '30-85',
            'Duplo kućište ( promenljivo )',
            'Standardno	',
            'Valjak sa unutrašnjim duplim ležajevima',
            'Standardno',
            'Kardansko vratilo (obr/min)',
            '540',
            'Težina ( kg )',
            '659 | 746 | 824',
        ],

        standardOprema1: 'MKS Plus',
        standardLi1: [
            ' - Propustna spojka u redukturu',
            ' - Duplospiralni rotor ( ušteda energije do 24 % )',
            ' - Kačenje KAT.I + II',
            ' - Radna tela: kovani čekići',
            ' - Hidraulični bočni pomak',
            ' - Hidraulični vertikalni ugao pomeranja – 65 º do +90º',
            ' - Mehanički amortizer',
            ' - Jak dupli paralelogram za regulaciju ugla mulčara',
            ' - Duplo kućište mulčera – promenljivo',
            ' - Limene zaštitne zavesice napred, gumena zaštitna zavesica pozadi',
            ' - Hidraulična blokada bočnog pomeranja',
            ' - Potporni valjak podesiv po visini',
            ' - Promenljive saonice',
            ' - Jednostavno održavanje – podmazivanje',
            ' - Plivajuće kačenje',
            ' - Potporna noga',
        ],

        standardOprema2: 'Dodatna oprema:',
        standardLi2: [
            ' - Kardan V 10 sa jednim zglobom',
            ' - Kardan W 65 sa duplim zglobom',
        ],

        brand: 'INO',
        category: 'Mulčeri'
    },
    {
        _id: '7',
        nameUrl: 'mulcer-mkm-130-160',
        productHeader: 'MKM 130-160',
        className: `mulcer-mkm-img`,
        desc1: 'Mulčer MKM upotrebljava se u ratarstvu, voćarstvu i u komunalne namene. Koristi se za usitnjavanje trave i žbunja ..',
        desc2: 'Mulčer MKM upotrebljava se u ratarstvu, voćarstvu i u komunalne namene. Koristi se za usitnjavanje trave i žbunja na zapuštenim terenima i grana debljine do 5 cm.',

        teh_kar: 'Tehničke Karakteristike',
        t1LeftHeader: 'Mulčer MKM 130-160',

        desc3: 'Predviđen je za intezivan rad. S njim možemo raditi iza traktora i pored traktora, čisti nasipe i kanale. Radi pod uglom od – 65 do + 90º. Mulčer MKM možemo koristiti kod mulčiranja nasipa u kombinaciji sa prednjim ELITE ili EURO. Tako radimo u jednom prohodu duple širine i s time štedimo na vremenu i potrošnji energije. Raspodela radnih tela na rotoru u duploj spirali štedi potrošnju energije do 24%.',

        table1: [
            'Model',
            'MKM 1303 | MKM 160',
            'Radna širina (cm)',
            '132 | 162',
            'Ukupna širina (cm)',
            '152 | 182',
            'Efikasnost (ha/sat)',
            '0,9-1,1 | 1,0-1,3',
            'Preporučena snaga (kW/KS)',
            '30-40/40-55 | 38-50/50-70',
            'Minimalna težina traktora ( kg )',
            '1800 | 2200',
            'Minimalna širina traktora ( cm )',
            '160 | 180',
            'Broj čekića ( kom )',
            '16 | 20',
            'Visina odkosa min-max (mm)',
            '30-80',
            'Kardansko vratilo (obr/min)',
            '540',
            'Težina (kg)',
            '546 | 587',
        ],

        standardOprema1: 'Mulčer MKM',
        standardLi1: [
            ' - Propustna spojka u redukturu',
            ' - Duplospiralni rotor ( ušteda energije do 24 % )',
            ' - Kačenje KAT.I + II',
            ' - Radna tela: kovani čekići',
            ' - Hidraulični bočni pomak',
            ' - Hidraulični vertikalni ugao pomeranja – 65 º do +90º',
            ' - Mehanički amortizer',
            ' - Jak dupli paralelogram za regulaciju ugla mulčara',
            ' - Plivajuće kačenje',
            ' - Potporna noga',
            ' - Potporni valjak podesiv po visini',
            ' - AGRI ležajevi ( standard )',
            ' - Promenljive saonice ',
            ' - Jednostavno održavanje – podmazivanje',
            ' - Jednostavno zatezanje remena',
            ' - Limene zaštitne zavesice',
        ],

        standardOprema2: 'Dodatna oprema:',
        standardLi2: [
            ' - Kardan',
        ],


        brand: 'INO',
        category: 'Mulčeri'
    },
    {
        _id: '8',
        nameUrl: 'mulcer-mkm-190-225-245',
        productHeader: 'MKM 190-225-245',
        className: `mulcer-mkm-img`,
        desc1: 'Mulčer MKM upotrebljava se u ratarstvu, voćarstvu i u komunalne namene. Koristi se za usitnjavanje trave i žbunja ..',
        desc2: 'Mulčer MKM upotrebljava se u ratarstvu, voćarstvu i u komunalne namene. Koristi se za usitnjavanje trave i žbunja na zapuštenim terenima i grana debljine do 5 cm.',

        teh_kar: 'Tehničke Karakteristike',
        t1LeftHeader: 'Mulčer MKM 190-225-245',

        desc3: 'Predviđen je za intezivan rad. S njim možemo raditi iza traktora i pored traktora, čisti nasipe i kanale. Radi pod uglom od – 65 do + 90º. Mulčer MKM možemo koristiti kod mulčiranja nasipa u kombinaciji sa prednjim ELITE ili EURO. Tako radimo u jednom prohodu duple širine i s time štedimo na vremenu i potrošnji energije. Raspodela radnih tela na rotoru u duploj spirali štedi potrošnju energije do 24%.',

        table1: [
            'Model',
            'MKM 190 | MKM 225 | MKM 245',
            'Radna širina (cm)',
            '192 | 227 | 242',
            'Ukupna širina (cm)',
            '212 | 247 | 262',
            'Efikasnost (ha/sat)',
            '1,2-1,6 | 1,5-2,1  | 1,6-2,2',
            'Preporučena snaga (kW/KS)',
            '53-70/70-95 | 60-80/80-110 | 65-90/90-120',
            'Minimalna težina traktora ( kg )',
            '2400 | 2600 | 2800',
            'Minimalna širina traktora ( cm )',
            '200',
            'Broj čekića ( kom )',
            '24 | 28 | 30',
            'Visina odkosa min-max (mm)',
            '30-80',
            'Kardansko vratilo (obr/min)',
            '540',
            'Težina (kg)',
            '684 | 765 | 890',
        ],

        standardOprema1: 'Mulčer MKM',
        standardLi1: [
            ' - Propustna spojka u redukturu',
            ' - Duplospiralni rotor ( ušteda energije do 24 % )',
            ' - Kačenje KAT.I + II',
            ' - Radna tela: kovani čekići',
            ' - Hidraulični bočni pomak',
            ' - Hidraulični vertikalni ugao pomeranja – 65 º do +90º',
            ' - Mehanički amortizer',
            ' - Jak dupli paralelogram za regulaciju ugla mulčara',
            ' - Plivajuće kačenje',
            ' - Potporna noga',
            ' - Potporni valjak podesiv po visini',
            ' - AGRI ležajevi ( standard )',
            ' - Promenljive saonice ',
            ' - Jednostavno održavanje – podmazivanje',
            ' - Jednostavno zatezanje remena',
            ' - Limene zaštitne zavesice',
        ],

        standardOprema2: 'Dodatna oprema:',
        standardLi2: [
            ' - Kardan',
        ],


        brand: 'INO',
        category: 'Mulčeri'
    },
    {
        _id: '8',
        nameUrl: 'mulcer-mkl',
        productHeader: 'Mulčer MKL',
        className: `mulcer-mkl-img`,
        desc1: 'Mulčer MKL upotrebljava se u ratarstvu za usitnjavanje biljnih ostataka i u komunalne namene. Drobe grane debljine do 3 cm..',
        desc2: 'Mulčer MKL upotrebljava se u ratarstvu za usitnjavanje biljnih ostataka i u komunalne namene. Drobe grane debljine do 3 cm.',

        teh_kar: 'Tehničke Karakteristike',
        t1LeftHeader: 'Mulčer MKL',

        desc3: 'Predviđen je za manje traktore i manje intezivan rad. S njim možemo raditi pored traktora i iza traktora, čisti nasipe i kanale. Radi pod uglom od – 65 do + 90 º. Raspodela radnih tela na rotoru u duploj spirali štedi potrošnju energije do 24 %.',

        table1: [
            'Model',
            'MKL 115 | MKL 130 | MKL 150',
            'Radna širina (cm)',
            '116 | 129 | 145',
            'Ukupna širina (cm)',
            '134 | 147 | 163',
            'Efikasnost (ha/sat)',
            '0,6-0,9 | 0,7-0,9  | 0,8-1,0',
            'Preporučena snaga (kW/KS)',
            '30-45/40-60 | 30-45/40-60 | 30-45/40-60',
            'Minimalna težina traktora ( kg )',
            '1600 | 1600 | 1800',
            'Minimalna širina traktora ( cm )',
            '120',
            'Broj čekića ( kom )',
            '16 | 18 | 20',
            'Visina odkosa min-max (mm)',
            '15-60',
            'Kardansko vratilo (obr/min)',
            '540',
            'Težina (kg)',
            '329 | 359 | 384',
        ],

        standardOprema1: 'Mulčer MKL ',
        standardLi1: [
            ' - Propustna spojka u redukturu',
            ' - Duplospiralni rotor ( ušteda energije do 24 % )',
            ' - Kačenje KAT.I + II',
            ' - Čekići na karikama ili Y – noževi opcija ili komunalni čekići na karikama – opcija',
            ' - Hidraulični bočni pomak',
            ' - Hidraulični vertikalni ugao pomeranja – 65 º do +90º',
            ' - Automatski zatezač remena',
            ' - Potporna noga',
            ' - Plivajuće kačenje',
            ' - Izbacivanje malčirane mase iza valjka',
            ' - Potporni valjak podesiv po visini',
            ' - AGRI ležajevi ( standard )',
            ' - Promenljive saonice ',
            ' - Jednostavno održavanje – podmazivanje',
            ' - Gumena zaštitna zavesica',
            ' - Limene zaštitne zavesice',
        ],

        standardOprema2: 'Dodatna oprema:',
        standardLi2: [
            ' - Kardan',
        ],
        brand: 'INO',
        category: 'Mulčeri'
    },
    {
        _id: '9',
        nameUrl: 'mulcer-frost',
        productHeader: 'Mulčer FORST',
        className: `mulcer-frost-img`,
        desc1: 'Mulčer FORST se upotrebljava u šumarstvu, poljoprivredii za komunalne namene za drobljenje grana i drveća debljine do 25 cm..',
        desc2: 'Mulčer FORST se upotrebljava u šumarstvu, poljoprivredii za komunalne namene za drobljenje grana i drveća debljine do 25 cm ( sa vidio čekićima drobimo grane i drveće debljine do 25 cm ).',

        teh_kar: 'Tehničke Karakteristike',
        t1LeftHeader: 'Mulčer FORST',

        desc3: 'Prednosti tog mulčera su robustna konstrukcija kućišta mulčer i rotora. Čekići se okrećuoko svoje osovine za 360º. Zbog toga se čekići kod preopterećenja sakriju u rotor i ne može doći do oštećenja.',

        table1: [
            'Model',
            'FORST 180 | FORST 225',
            'Radna širina (cm)',
            '180 | 223',
            'Ukupna širina (cm)',
            '212 | 255',
            'Preporučena snaga (kW/KS)',
            '65-90/90-120 | 90-110/120-150',
            'Broj čekića ( kom )',
            '28 | 36',
            'Visina odkosa min-max (mm)',
            '10-40',
            'Kardansko vratilo (obr/min)',
            '1000',
            'Hidraulično otvaranje poklopca',
            'da',
            'Promenljivi protiv noževi u dva reda',
            'da',
            'Prednji zaštitni lanci ( 2 reda )',
            'da',
            'Dimenzije ( Š/D/V )',
            '128/212/111 | 128/255/111',
            'Težina ( kg )',
            '1210 | 1410',
        ],

        standardOprema1: 'Mulčer MKL ',
        standardLi1: [
            ' - Mulčer ima promenljive protinoževe što omogućava kvalitetnije drobljenje mase',
            ' - Na zadnjem delu kućišta mulčera je ugrađen poklopac koji se otvara i zatvara pomoću hidraulike',
            ' - Mulčer ima zaštitni podesiv luk, koji preprečava padanje većih grana i drveća po traktoru.'
        ],

        standardOprema2: 'Dodatna oprema:',
        standardLi2: [
            ' - Pozovite',
        ],

        brand: 'INO',
        category: 'Mulčeri'
    },
    {
        _id: '10',
        nameUrl: 'mulcer-elite',
        productHeader: 'Mulčer ELITE',
        className: `mulcer-elite-img`,
        desc1: 'Mulčer ELITE je predviđen za sve poljoprivredne površine.Potrebna traktorska snaga: 42 – 75 kW. Može se primeniti..',
        desc2: 'Mulčer ELITE L predviđen je za svestranuprimenu na svim poljoprivrednim površinama, za održavnje zelenih površina i zapuštenih terena.',

        teh_kar: 'Tehničke Karakteristike',
        t1LeftHeader: 'Mulčer ELITE ',

        desc3: 'Mulčer ELITE možemo primeniti kod usitnjavanja svih žetvenih ostataka, kao i za usitnjavanje ostataka rezidbe u voćnjacima i vinogradima za drobljenje grana debljine do 5 cm. Konstrukcija mulčera je pojačana. Ima pojačan okvir i jače nosače luka. Raspodela radnih tela u duploj spirali spirali štedi potrošnju energije do 24 %.',

        table1: [
            'Model',
            'ELITE 225 | ELITE 245 | ELITE 270',
            'Radna širina (cm)',
            '227 | 242 | 272',
            'Ukupna širina (cm)',
            '247 | 262 | 292',
            'Efikasnost (ha/sat)',
            '1,5/2,1 | 1,6/2,2 | 1,8/2,5',
            'Preporučena snaga (kW/KS)',
            '42-55/55-75 | 48-65/65-90 | 55-75/75-100',
            'Mehan.podeš. boč. pomaka (cm)',
            '247 | 262 | 292',
            'Broj čekića ( kom )',
            '28 | 30 | 34',
            'Visina odkosa min-max (mm)',
            '30-80',
            'Kardansko vratilo (obr/min)',
            '540',
            'Dimenzije ( Š/D/V )',
            '100/247/100 | 100/262/100 | 100/292/100',
            'Težina ( kg )',
            '554 | 596 | 632',
        ],

        standardOprema1: 'Mulčer Elite ',
        standardLi1: [
            ' - Propustna spojka u redukturu',
            ' - Duplospiralni rotor ( ušteda energije do 24 % )',
            ' - Jake vodilice luka',
            ' - Robustno kućište',
            ' - Kačenje u tri tačke KAT I + II',
            ' - Bočna hidraulična kosilica BD ili BDR – opcija',
            ' - Limene zaštitne zavesice',
            ' - Čekići ( standard ) ili Y – nož ( opcija )',
            ' - Zadnji valjak podesiv po visini ( standard )',
            ' - Promenljive saonice',
            ' - Jednostavno održavanje – podmazivanje',
            ' - Štit remena – jednostavno zatezanje remena',
            ' - AGRI ležajevi',
            ' - Mehaničko podešavanje bočnog pomaka',
            ' - Plivajuće kačenje',
        ],

        standardOprema2: 'Dodatna oprema:',
        standardLi2: [
            ' - Hidraulični bočni pomak',
            ' - Bočna rotaciona hidraulična kosačica – BDR ( sa rezervoarom, hidr. pumpom )',
            ' - Bočna rotaciona hidraulična kosačica – BD ( pogon sa hidr. pumpe traktora )',
            ' - Bočna rot.hidr.kosačica – BD LEVI ( pogon sa hidr. pumpe traktora )',
            ' - HA30 – hidraulički agregat za BD ili BDL ( rezervoar + pumpa )',
            ' - Kardan',
            ' - HERBI 100 – prskalica za herbicide, jedna strana / dve strane',
            'Točkovi'
        ],

        brand: 'INO',
        category: 'Mulčeri'
    },
    {
        _id: '11',
        nameUrl: 'mulcer-elite-l-115-130',
        productHeader: 'Mulčer ELITE L 115-130',
        className: `mulcer-elite-l-img`,
        desc1: 'Mulčer ELITE L je predviđen za sve poljoprivredne površine.Potrebna traktorska snaga: 42 – 75 kW. Može se primeniti..',
        desc2: 'Mulčer ELITE L predviđen je za svestranuprimenu na svim poljoprivrednim površinama, za održavnje zelenih površina i zapuštenih terena.',

        teh_kar: 'Tehničke Karakteristike',
        t1LeftHeader: 'Mulčer ELITE L',

        desc3: 'Mulčer ELITE L možemo primeniti kod usitnjavanja svih žetvenih ostataka, kao i za usitnjavanje ostataka rezidbe u voćnjacima i vinogradima za drobljenje grana debljine do 5 cm. Konstrukcija je vrlo robusna i predviđena za intenzivno korišćenje. Raspodela radnih tela u duploj spirali štedi potrošnju energije do 24%',

        table1: [
            'Model',
            'ELITE L 115 | ELITE L 130',
            'Radna širina (cm)',
            '117 | 132',
            'Ukupna širina (cm)',
            '137 | 152',
            'Efikasnost (ha/sat)',
            '0,7-1,0 | 0,9-1,1',
            'Preporučena snaga (kW/KS)',
            '19-25/25-35 | 23-30/30-40',
            'Mehan.podeš. boč. pomaka (cm)',
            '40',
            'Broj čekića ( kom )',
            '14 | 16 ',
            'Visina odkosa min-max (mm)',
            '30-80',
            'Kardansko vratilo (obr/min)',
            '540',
            'Dimenzije ( Š/D/V )',
            '100/137/100 | 100/152/100',
            'Težina ( kg )',
            '325 | 334',
        ],

        standardOprema1: 'Mulčer Elite L',
        standardLi1: [
            ' - Propustna spojka u reduktoru',
            ' - Duplospiralni rotor ( ušteda energije do 24 % )',
            ' - Mehaničko podešavanje bočnog pomaka',
            ' - Jake vodilice luka',
            ' - Podporna noga',
            ' - Kačenje u tri tačke KAT I + II',
            ' - Plivajuće kačenje',
            ' - Pomerljiva hidraulična rotaciona kosilica ( BDR ili BD ) – opcija',
            ' - Limene zaštitne zavesice',
            ' - Čekići ( standard ) ili Y – nož ( opcija )',
            ' - Zadnji valjak podesiv po visini ( standard )',
            ' - AGRI ležajevi ( standard )',
            ' - Promenljive saonice',
            ' - Jednostavno održavanje – podmazivanje',
            ' - Štit remena – jednostavno zatezanje remena ',
        ],

        standardOprema2: 'Dodatna oprema:',
        standardLi2: [
            ' - Hidraulični bočni pomak',
            ' - Bočna rotaciona hidraulična kosačica – BDR ( sa rezervoarom, hidr. pumpom )',
            ' - Bočna rotaciona hidraulična kosačica – BD ( pogon sa hidr. pumpe traktora )',
            ' - Bočna rot.hidr.kosačica – BD LEVI ( pogon sa hidr. pumpe traktora )',
            ' - HA30 – hidraulički agregat za BD ili BDL ( rezervoar + pumpa )',
            ' - Kardan',
            ' - HERBI 100 – prskalica za herbicide, jedna strana / dve strane',
            'Točkovi'
        ],


        brand: 'INO',
        category: 'Mulčeri',
    },
    {
        _id: '12',
        nameUrl: 'mulcer-elite-l-160-190',
        productHeader: 'Mulčer ELITE L 160-190',
        className: `mulcer-elite-l-img`,
        desc1: 'Mulčer ELITE L je predviđen za sve poljoprivredne površine.Potrebna traktorska snaga: 42 – 75 kW. Može se primeniti..',
        desc2: 'Mulčer ELITE L predviđen je za svestranuprimenu na svim poljoprivrednim površinama, za održavnje zelenih površina i zapuštenih terena.',

        teh_kar: 'Tehničke Karakteristike',
        t1LeftHeader: 'Mulčer ELITE L',

        desc3: 'Mulčer ELITE L možemo primeniti kod usitnjavanja svih žetvenih ostataka, kao i za usitnjavanje ostataka rezidbe u voćnjacima i vinogradima za drobljenje grana debljine do 5 cm. Konstrukcija je vrlo robusna i predviđena za intenzivno korišćenje. Raspodela radnih tela u duploj spirali štedi potrošnju energije do 24%',

        table1: [
            'Model',
            'ELITE L 160 | ELITE L 190',
            'Radna širina (cm)',
            '162 | 192',
            'Ukupna širina (cm)',
            '182 | 212',
            'Efikasnost (ha/sat)',
            '1,0-1,3 | 1,2-1,6',
            'Preporučena snaga (kW/KS)',
            '27-35/35-48  | 34-45/45-60',
            'Mehan.podeš. boč. pomaka (cm)',
            '40',
            'Broj čekića ( kom )',
            '20 | 24 ',
            'Visina odkosa min-max (mm)',
            '30-80',
            'Kardansko vratilo (obr/min)',
            '540',
            'Dimenzije ( Š/D/V )',
            '100/182/100 | 100/212/100',
            'Težina ( kg )',
            '405 | 451',
        ],

        standardOprema1: 'Mulčer Elite L',
        standardLi1: [
            ' - Propustna spojka u reduktoru',
            ' - Duplospiralni rotor ( ušteda energije do 24 % )',
            ' - Mehaničko podešavanje bočnog pomaka',
            ' - Jake vodilice luka',
            ' - Podporna noga',
            ' - Kačenje u tri tačke KAT I + II',
            ' - Plivajuće kačenje',
            ' - Pomerljiva hidraulična rotaciona kosilica ( BDR ili BD ) – opcija',
            ' - Limene zaštitne zavesice',
            ' - Čekići ( standard ) ili Y – nož ( opcija )',
            ' - Zadnji valjak podesiv po visini ( standard )',
            ' - AGRI ležajevi ( standard )',
            ' - Promenljive saonice',
            ' - Jednostavno održavanje – podmazivanje',
            ' - Štit remena – jednostavno zatezanje remena ',
        ],

        standardOprema2: 'Dodatna oprema:',
        standardLi2: [
            ' - Hidraulični bočni pomak',
            ' - Bočna rotaciona hidraulična kosačica – BDR ( sa rezervoarom, hidr. pumpom )',
            ' - Bočna rotaciona hidraulična kosačica – BD ( pogon sa hidr. pumpe traktora )',
            ' - Bočna rot.hidr.kosačica – BD LEVI ( pogon sa hidr. pumpe traktora )',
            ' - HA30 – hidraulički agregat za BD ili BDL ( rezervoar + pumpa )',
            ' - Kardan',
            ' - HERBI 100 – prskalica za herbicide, jedna strana / dve strane',
            'Točkovi'
        ],


        brand: 'INO',
        category: 'Mulčeri',
    },
]


const both = [...FpmMulcariList, ...InoBreziceMulceri];



export { FpmMulcariList, InoBreziceMulceri, both };

